### ISSUE TITLE
gather-deps.sh fails

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/meteor-spk#12]
`./gather-deps.sh 1.2` fails for me on the following command:

```
readlink -f /home/david/.meteor/packages/meteor-tool/1.1.7/mt-os.linux.x86_64/dev_bundle
```

That file doesn't exist:

```
$ ls /home/david/.meteor/packages/meteor-tool/
1.1.10  1.1.3
```

**Comment by zarvox** [comment]
Try `./gather-deps.sh 1.2.1`?  or whatever version you get from `meteor --version`

**Comment by dwrensha** [comment]
Indeed, I just needed to try `make METEOR_VERSION=1.2.1`.

**Comment by kentonv** [comment]
Hmm. I suspect if you use any meteor command in a project that is pinned to 1.2, Meteor will download that version, thus fixing this problem.
