### ISSUE TITLE
sandstorm-pkgdef.capnp should be created inside .sandstorm

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/meteor-spk#21]
In my Meteor app `sandstorm-pkgdef.capnp` was created in the root of my project tree, but in documentation it seems that it is commonly inside `.sandstorm`. It would be great if this would be unified.

**Comment by kentonv** [comment]
If you are using `vagrant-spk`, then the config goes in `.sandstorm`. You should not use `meteor-spk` directly if you are using `vagrant-spk`. I'll update the readme.

**Comment by mitar** [comment]
No. I was not using `vagrant-spk`. But I am saying that reading various documentation makes it really hard to understand how things relate. I think `meteor-spk` should put its file into `.sandstorm` as well. The same as `vagrant-spk`. You could update `sandstorm-pkgdef.capnp` template generated from `meteor-spk` to expect to be inside `.sandstorm`.

**Comment by mitar** [comment]
Forget about my comment above. I just read your commit. :-)
