### ISSUE TITLE
Support Meteor 1.4

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/meteor-spk#24]
Meteor 1.4 now uses Node V4.x. I forget the exact version but it's in the changelog. Meteor-spk will now need to ship Node v0.10, v4 and, in a few months, v6.

Meteor 1.4 also expects that you have a development toolchain installed, as it no longer ships binary modules for Meteor packages built against its shipped Node. Not sure what effect if any that has on meteor-spk, above and beyond having to install build-essential if an app's package needs are remotely complex.

As a heads-up, it looks like Meteor 1.5 will transition heavily to Apollo, meaning the Mongo dependency will go away and can be replaced with SQLite/Postgres/MySQL/Redis/whatever.

**Comment by ocdtrekkie** [comment]
This may be an issue for Wekan soon, since they're using a dependency-updating bot which is repeatedly making PRs to update things that require Meteor 1.4. https://github.com/wekan/wekan/pull/660

**Comment by dwrensha** [comment]
meteor-spk v0.3.0, released a few weeks ago, supports Meteor 1.4.

**Comment by paulproteus** [comment]
Hi @ndarilek ,

I thought you might be interested to know that I'm tackling this now. I did some research here, from the vagrant-spk perspective: https://github.com/sandstorm-io/vagrant-spk/issues/193

I'll probably be filing a few other issues about this, as time goes on and I attempt to understand the full situation. I agree that the Meteor 1.4 is different from Meteor 1.3-and-before.

**Comment by ocdtrekkie** [comment]
I propose closing this, as of https://github.com/sandstorm-io/vagrant-spk/pull/231

meteor-spk and vagrant-spk "work" with 1.4-1.6. It could be argued if work needs to be done to support other databases, we should call that a feature request, rather than a request for version support. (Since current Meteor-based apps should work with the existing setup on 1.6.)

**Comment by kentonv** [comment]
Yeah this is way obsolete...
