### ISSUE TITLE
mmap error while packing

### ISSUE THREAD

**Issue by gischer** [sandstorm-io/meteor-spk#34]
I'm tryiing to package a meteor app using meteor-spk on an Ubuntu 18.04.02 LTS.
My command was
`meteor-spk pack <application name>`

I'm getting the following error:
```
*** Uncaught exception ***
kj/filesystem-disk-unix.c++:352: failed: mmap: Invalid argument
stack: 61734c 4b2f5e 4b2752 6396a1 6712e4 6734cd 66ce1e 66bf88 66ee37 66d91c 66bf88 66ee37 66d91c 66bf88 66ee37 66d91c 66bf88 65ee14 65ec19 6368de 637257 6374f3 63bee4 63c800 4aef2b 4afb3e 5c360d 5cc30f 5cbb33 5cbafc 64d413

```
This happens right after a bunch of node output, saying things like

`added 150 packages from 109 contributors and audited 326 packages in 5.764s`

I'm kind of gobsmacked that I'm getting an mmap error here, and I don't know where to begin looking for a problem.

**Comment by ocdtrekkie** [comment]
This definitely seems to be a capnproto flavored question, perhaps @kentonv can look into it? I don't think I've seen it come up before for Sandstorm-related things.

https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/kj/filesystem-disk-unix.c%2B%2B#L348

**Comment by gischer** [comment]
I don't have enough experience with meteor-spk to know whether this matters, but I'm seeing an oddity.

The log of the `meteor-spk pack` command says this:
```
found 5 vulnerabilities (4 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```
But when I run `meteor npm audit fix` in the same directory, it says

```
up to date in 1.622s
fixed 0 of 0 vulnerabilities in 796 scanned packages

```
Could this be related?

**Comment by ocdtrekkie** [comment]
I kinda doubt it, but I'm curious what those vulnerabilities are. Did you try just `npm audit`, and is there a reason the packages it lists aren't able to be updated?

**Comment by gischer** [comment]
I just had to update npm, apparently meteor has its own version squirreled away somewhere, but npm audit now has the same version and gives the same result:  No vulnerabilities.  

Which leaves me scratching my head.  Apparently meteor-spk has yet another version of npm it keeps somewhere?  Or maybe it has a cached set of packages?

**Comment by ocdtrekkie** [comment]
Meteor keeping it's own version of Node sounds kinda familiar. I've found statements that Meteor bundles it's own NPM, and that it can be a different version of NPM than your system's NPM, etc. `meteor npm install` is a thing.

**Comment by gischer** [comment]
Yeah, the truly bizarre thing is that I've discovered that when you do "meteor build" as meteor-spk does, it seems to use <em>yet another</em> version of node.

**Comment by gischer** [comment]
Ok, I was off working on a different meteor port and just returned to this one.  I have discovered that if I comment out the pgp-signature and pgp-keyring entries of the sandstorm-pkgdef.capnp file, the error goes away.

The most likely reason to get this error from mmap is that the file you are trying to map into memory does not, in fact, exist.  So I expect that I was specifying where to find these files incorrectly.  They are at the top level of my meteor source tree and I referred to them as

`pgpSignature = embed "signature"
pgpKeyring = embed "pgp-keyring"`

AFAICT, I have the files by those names available at the top of my source tree, where the sandstorm-pkgdef.capnp file also is.  But perhaps that's not what spk expects?

I'd love a hint or poke in the right direction on this, but it seems as though it's likely pilot error.  Close it.

**Comment by ocdtrekkie** [comment]
@gischer It's not something simple like the filename of pgpSignature being `pgp-signature` instead of `signature`, is it? It's a stupid ask, but since your keyring file is named like the examples but the signature not being, I figured I'd ask.

**Comment by gischer** [comment]
@ocdtrekkie I just checked your suggestion.  I changed the names of the files to both `pgpSignature` and `pgp-signature` and it didn't help.  But commenting them out does help.  In contrast, I just added a description.md and packaging was successful.  So, I think I've probably got something wrong with these files and I'm going to have to play with them more.
