### ISSUE TITLE
Meteor 2.3.x and Node 14 ?

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/meteor-spk#39]
Hi,
are there any plans to sometime try to upgrade meteor-spk and Sandstorm to Meteor 2.3.x and Node 14 ?

There is some trying to upgrade Wekan in progress https://github.com/wekan/wekan/issues/3881

**Comment by zenhack** [comment]
I'm sure we'll do it at some point; for Sandstorm normally @kentonv updates dependencies when he does a release, so probably not *too* long. But I don't know off hand if node-capnp works on node 14 yet, which will need to be fixed if not.

**Comment by zenhack** [comment]
For meteor-spk we haven't been in the habit of updating it regularly, but in theory there's no reason we wouldn't update to the latest meteor version.

**Comment by xet7** [comment]
When using Node.js 12, I have usually just changed node binary to newest 12.x version:
https://releases.wekan.team/meteor-spk/

I have not made other changes.

Although, for major node version, meteor-spk could maybe need other changes.

**Comment by zenhack** [comment]
This has become somewhat more important for Sandstorm itself, since Sandstorm has updated to node 14 --- but the meteor test app has not, and I *suspect* the discrepancy, combined with a shared node-capnp build, may be responsible.

**Comment by xet7** [comment]
@zenhack 

Wow thanks a lot for info !!! I did not know Sandstorm now has node 14. So when there is Wekan with node 14, it could work on Sandstorm? And meteor-spk could be updated? I'll try can I get newest Meteor and Node 14 working with Wekan.

**Comment by zenhack** [comment]
Yeah, node 14 is used by the last release that @kentonv kicked out. We will have to update meteor-spk to use it as well.

**Comment by zenhack** [comment]
meteor-spk 0.6.0 includes these, we should close this.
